Error: Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/__init__.py", line 378, in execute
    from .blender.exp import gltf2_blender_export
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 22, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 19, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_nodes
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 24, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_mesh
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 20, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_primitives
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blende... truncated

  
  
  
  Error: Traceback (most recent call last):
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/__init__.py", line 378, in execute
    from .blender.exp import gltf2_blender_export
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 22, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 19, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_nodes
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 24, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_mesh
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 20, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_primitives
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 25, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_materials
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 20, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_texture_info, gltf2_blender_export_keys
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture_info.py", line 19, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_texture
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_texture.py", line 22, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_gather_image
  File "/usr/share/blender/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_image.py", line 19, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
